services:
  app:
    volumes:
      - ./app/src:/app
    # need workers=1 for debugging so file changes will be picked up
    command: ["./dbupgrade_and_run.sh", "gunicorn", "--reload", "--bind", "0.0.0.0:5000", "--log-level", "info", 
              "--workers=1", "--threads=4", 
              "--access-logfile", "${ACCESS_LOG}", "--access-logformat", '%({x-forwarded-for}i)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"', 
              "--timeout", "120", "app_server:app"]
