"""add sponsor race, levels, benefits

Revision ID: f9e85406526b
Revises: 3a692c4cf519
Create Date: 2019-03-10 16:54:43.349000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9e85406526b'
down_revision = '3a692c4cf519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsorbenefit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benefit', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsorrace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race', sa.String(length=256), nullable=True),
    sa.Column('raceshort', sa.String(length=256), nullable=True),
    sa.Column('racedirector', sa.String(length=256), nullable=True),
    sa.Column('raceurl', sa.String(length=2047), nullable=True),
    sa.Column('sponsorurl', sa.String(length=2047), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('couponprovider', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsorlevel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('minsponsorship', sa.Integer(), nullable=True),
    sa.Column('couponcount', sa.Integer(), nullable=True),
    sa.Column('display', sa.Boolean(), nullable=True),
    sa.Column('maxallowed', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['sponsorrace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sponsorlevelbenefit',
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('benefit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['benefit_id'], ['sponsorbenefit.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['sponsorlevel.id'], )
    )
    op.alter_column('client', 'clientAddr',
               existing_type=mysql.VARCHAR(length=13),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('client', 'clientPhone',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=13),
               existing_nullable=True)
    op.alter_column('course', 'isStandard',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('event', 'isOnCalendar',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('service', 'isCalendarBlocked',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('tag', 'isBuiltIn',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('user', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('tag', 'isBuiltIn',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('service', 'isCalendarBlocked',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('event', 'isOnCalendar',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('course', 'isStandard',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('client', 'clientPhone',
               existing_type=sa.String(length=13),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
    op.alter_column('client', 'clientAddr',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=13),
               existing_nullable=True)
    op.drop_table('sponsorlevelbenefit')
    op.drop_table('sponsorlevel')
    op.drop_table('sponsorrace')
    op.drop_table('sponsorbenefit')
    # ### end Alembic commands ###
