"""races: add viewkey

Revision ID: 280a85bbb82a
Revises: b70822f1b8ed
Create Date: 2021-03-13 12:14:44.675807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '280a85bbb82a'
down_revision = 'b70822f1b8ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('race', sa.Column('viewkey', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('race', 'viewkey')
    # ### end Alembic commands ###
