"""event table: add invoiceDocId

Revision ID: 4ffb01ddd6eb
Revises: d7dc8e8e2801
Create Date: 2024-09-12 14:34:40.119389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ffb01ddd6eb'
down_revision = 'd7dc8e8e2801'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('invoiceDocId', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'invoiceDocId')
    # ### end Alembic commands ###

