"""sponsorrace: add timezone

Revision ID: 5f25fdd3309f
Revises: 08bc44cc351f
Create Date: 2022-11-29 12:14:57.225015

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = '5f25fdd3309f'
down_revision = '08bc44cc351f'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsorrace', sa.Column('timezone', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # default sponsorrace.is_active to True
    sponsorrace = table('sponsorrace',
                     column('timezone', sa.Text()))
    op.execute(
        sponsorrace.update().\
            values({'timezone':op.inline_literal('US/Eastern')})
    )

def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsorrace', 'timezone')
    # ### end Alembic commands ###

