"""sponsorrace: add email_from, query_cc, agreement_cc

Revision ID: 7ac6ef1d0797
Revises: 5f25fdd3309f
Create Date: 2024-01-29 15:26:52.208280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac6ef1d0797'
down_revision = '5f25fdd3309f'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsorrace', sa.Column('email_from', sa.Text(), nullable=True))
    op.add_column('sponsorrace', sa.Column('query_cc', sa.Text(), nullable=True))
    op.add_column('sponsorrace', sa.Column('agreement_cc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsorrace', 'agreement_cc')
    op.drop_column('sponsorrace', 'query_cc')
    op.drop_column('sponsorrace', 'email_from')
    # ### end Alembic commands ###

