"""addon.fee, service.fee, feebasedon.fee are numeric

Revision ID: b21afd3664b3
Revises: 4ffb01ddd6eb
Create Date: 2024-12-17 14:57:35.659987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b21afd3664b3'
down_revision = '4ffb01ddd6eb'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addon', 'fee',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('feebasedon', 'fee',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('service', 'fee',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service', 'fee',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('feebasedon', 'fee',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('addon', 'fee',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    # ### end Alembic commands ###

