"""add version_id

Revision ID: b718a3578c4a
Revises: 5f1f613f2fc2
Create Date: 2019-05-01 14:43:16.458000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b718a3578c4a'
down_revision = '5f1f613f2fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addon', sa.Column('version_id', sa.Integer(), nullable=False))
    op.add_column('client', sa.Column('version_id', sa.Integer(), nullable=False))
    op.add_column('contract', sa.Column('version_id', sa.Integer(), nullable=False))
    op.add_column('contractblocktype', sa.Column('version_id', sa.Integer(), nullable=False))
    op.add_column('contracttype', sa.Column('version_id', sa.Integer(), nullable=False))
    op.add_column('course', sa.Column('version_id', sa.Integer(), nullable=False))
    op.alter_column('course', 'isStandard',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('daterule', sa.Column('version_id', sa.Integer(), nullable=False))
    op.add_column('event', sa.Column('version_id', sa.Integer(), nullable=False))
    op.alter_column('event', 'isOnCalendar',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('eventavailabilityexception', sa.Column('version_id', sa.Integer(), nullable=False))
    op.add_column('feebasedon', sa.Column('version_id', sa.Integer(), nullable=False))
    op.add_column('feetype', sa.Column('version_id', sa.Integer(), nullable=False))
    op.add_column('lead', sa.Column('version_id', sa.Integer(), nullable=False))
    op.add_column('race', sa.Column('version_id', sa.Integer(), nullable=False))
    op.add_column('service', sa.Column('version_id', sa.Integer(), nullable=False))
    op.alter_column('service', 'isCalendarBlocked',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('sponsor', sa.Column('version_id', sa.Integer(), nullable=False))
    op.alter_column('sponsor', 'RegSiteUpdated',
               existing_type=mysql.ENUM('no', 'yes', 'n/a'),
               nullable=True)
    op.alter_column('sponsor', 'isLogoReceived',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('sponsor', 'isSponsorThankedFB',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('sponsor', 'isWebsiteUpdated',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('sponsorbenefit', sa.Column('version_id', sa.Integer(), nullable=False))
    op.add_column('sponsorlevel', sa.Column('version_id', sa.Integer(), nullable=False))
    op.alter_column('sponsorlevel', 'display',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('sponsorrace', sa.Column('version_id', sa.Integer(), nullable=False))
    op.alter_column('sponsorrace', 'isRDCertified',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('sponsorracedate', sa.Column('version_id', sa.Integer(), nullable=False))
    op.alter_column('sponsorracedate', 'beneficiary',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.alter_column('sponsorracedate', 'raceloc',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
    op.add_column('sponsorracevbl', sa.Column('version_id', sa.Integer(), nullable=False))
    op.add_column('state', sa.Column('version_id', sa.Integer(), nullable=False))
    op.add_column('tag', sa.Column('version_id', sa.Integer(), nullable=False))
    op.alter_column('tag', 'isBuiltIn',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.add_column('templatetype', sa.Column('version_id', sa.Integer(), nullable=False))
    op.alter_column('user', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('templatetype', 'version_id')
    op.alter_column('tag', 'isBuiltIn',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('tag', 'version_id')
    op.drop_column('state', 'version_id')
    op.drop_column('sponsorracevbl', 'version_id')
    op.alter_column('sponsorracedate', 'raceloc',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.alter_column('sponsorracedate', 'beneficiary',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
    op.drop_column('sponsorracedate', 'version_id')
    op.alter_column('sponsorrace', 'isRDCertified',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('sponsorrace', 'version_id')
    op.alter_column('sponsorlevel', 'display',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('sponsorlevel', 'version_id')
    op.drop_column('sponsorbenefit', 'version_id')
    op.alter_column('sponsor', 'isWebsiteUpdated',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('sponsor', 'isSponsorThankedFB',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('sponsor', 'isLogoReceived',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('sponsor', 'RegSiteUpdated',
               existing_type=mysql.ENUM('no', 'yes', 'n/a'),
               nullable=False)
    op.drop_column('sponsor', 'version_id')
    op.alter_column('service', 'isCalendarBlocked',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('service', 'version_id')
    op.drop_column('race', 'version_id')
    op.drop_column('lead', 'version_id')
    op.drop_column('feetype', 'version_id')
    op.drop_column('feebasedon', 'version_id')
    op.drop_column('eventavailabilityexception', 'version_id')
    op.alter_column('event', 'isOnCalendar',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('event', 'version_id')
    op.drop_column('daterule', 'version_id')
    op.alter_column('course', 'isStandard',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('course', 'version_id')
    op.drop_column('contracttype', 'version_id')
    op.drop_column('contractblocktype', 'version_id')
    op.drop_column('contract', 'version_id')
    op.drop_column('client', 'version_id')
    op.drop_column('addon', 'version_id')
    # ### end Alembic commands ###
