"""add sponsorraceregcache table

Revision ID: 08bc44cc351f
Revises: 6f403f3025b2
Create Date: 2022-09-16 16:36:12.130144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08bc44cc351f'
down_revision = '6f403f3025b2'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sponsorraceregcache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.Text(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('last_modified_ts', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('removed_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sponsorraceregcache_event_id'), 'sponsorraceregcache', ['event_id'], unique=False)
    op.add_column('sponsorrace', sa.Column('cacheupdatets', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsorrace', 'cacheupdatets')
    op.drop_index(op.f('ix_sponsorraceregcache_event_id'), table_name='sponsorraceregcache')
    op.drop_table('sponsorraceregcache')
    # ### end Alembic commands ###

