"""add update_time to service, addon, contract tables

Revision ID: 10a716c12eb1
Revises: 2d83772a9194
Create Date: 2024-08-24 15:17:15.492507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a716c12eb1'
down_revision = '2d83772a9194'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addon', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('contract', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('service', sa.Column('update_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'update_time')
    op.drop_column('contract', 'update_time')
    op.drop_column('addon', 'update_time')
    # ### end Alembic commands ###

