"""sponsorrace: add viewkey

Revision ID: 321e28a8aa56
Revises: b70822f1b8ed
Create Date: 2021-03-13 13:11:00.110824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321e28a8aa56'
down_revision = 'b70822f1b8ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sponsorrace', sa.Column('viewkey', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sponsorrace', 'viewkey')
    # ### end Alembic commands ###
