"""increase length of all phone number fields to 20 characters

Revision ID: 3dd0e4c59adb
Revises: 4b35b5d71a46
Create Date: 2026-04-14 15:45:14.653603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3dd0e4c59adb'
down_revision = '4b35b5d71a46'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client', 'clientPhone',
               existing_type=mysql.VARCHAR(length=13),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('lead', 'phone',
               existing_type=mysql.VARCHAR(length=13),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('sponsorquerylog', 'phone',
               existing_type=mysql.VARCHAR(length=13),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('sponsorrace', 'rdphone',
               existing_type=mysql.VARCHAR(length=13),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sponsorrace', 'rdphone',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=13),
               existing_nullable=True)
    op.alter_column('sponsorquerylog', 'phone',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=13),
               existing_nullable=True)
    op.alter_column('lead', 'phone',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=13),
               existing_nullable=True)
    op.alter_column('client', 'clientPhone',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=13),
               existing_nullable=True)
    # ### end Alembic commands ###

