"""service.priority, event.isInvoiceInitiated, event.*notes Text

Revision ID: 778c5f399640
Revises: cab5fc3df18b
Create Date: 2025-02-27 12:11:36.603746

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '778c5f399640'
down_revision = 'cab5fc3df18b'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('isInvoiceInitiated', sa.Boolean(), nullable=True))
    op.alter_column('event', 'notes',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('event', 'contractApproverNotes',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('service', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'priority')
    op.alter_column('event', 'contractApproverNotes',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('event', 'notes',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)
    op.drop_column('event', 'isInvoiceInitiated')
    # ### end Alembic commands ###

