"""event table add contractSentReminderDate

Revision ID: 9b95b190721e
Revises: c89c718bee57
Create Date: 2026-04-21 14:30:59.121210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b95b190721e'
down_revision = 'c89c718bee57'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('contractSentReminderDate', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'contractSentReminderDate')
    # ### end Alembic commands ###

