"""add event.isContractUpdated

Revision ID: b70822f1b8ed
Revises: 5b79283feef9
Create Date: 2020-01-19 05:59:42.131000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = 'b70822f1b8ed'
down_revision = '5b79283feef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('isContractUpdated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    # set current data to default value False
    event = table('event',
        column( 'isContractUpdated', sa.Boolean() ),
    )
    op.execute(
        event.update().\
            values({'isContractUpdated':op.inline_literal(False)})
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'isContractUpdated')
    # ### end Alembic commands ###
