"""add client.ccEmails

Revision ID: c89c718bee57
Revises: f06e7dd7ecfa
Create Date: 2026-04-17 10:21:51.641165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89c718bee57'
down_revision = 'f06e7dd7ecfa'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('ccEmails', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'ccEmails')
    # ### end Alembic commands ###

