"""contract.block is text

Revision ID: cab5fc3df18b
Revises: fc9716e22e0f
Create Date: 2025-02-21 15:25:49.262844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cab5fc3df18b'
down_revision = 'fc9716e22e0f'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contract', 'block',
               existing_type=mysql.VARCHAR(length=2048),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contract', 'block',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=2048),
               existing_nullable=True)
    # ### end Alembic commands ###

