"""add priority to addon table

Revision ID: d7dc8e8e2801
Revises: 10a716c12eb1
Create Date: 2024-08-25 13:42:13.436100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7dc8e8e2801'
down_revision = '10a716c12eb1'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addon', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    from sqlalchemy.sql import table, column
    addon = table('addon',
                 column('priority', sa.Integer))
    op.execute(
        addon.update().\
            values(
                {'priority': op.inline_literal(10)}
            )
    )

def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addon', 'priority')
    # ### end Alembic commands ###

