"""remove serviceaddon table

Revision ID: fc9716e22e0f
Revises: b21afd3664b3
Create Date: 2024-12-18 16:50:03.419536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc9716e22e0f'
down_revision = 'b21afd3664b3'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serviceaddon')
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serviceaddon',
    sa.Column('service_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('addon_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['addon.id'], name='serviceaddon_ibfk_1'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name='serviceaddon_ibfk_2'),
    sa.PrimaryKeyConstraint('service_id', 'addon_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###

